#!/usr/bin/env python3
"""Fill xref-page.template.html from a payload and write the standalone page.

This is both the example builder and the reference implementation of the fill
step. Point --data at your own generator's --format json output and it works
unchanged; only the strings in FIELDS are project-specific.

  ./build-example.py                       # rebuild example/index.html
  ./build-example.py --check               # verify, write nothing (CI)
  ./build-example.py --data ../../../out.json --out /tmp/page.html

Substitution is done here, in code, and never by hand or by an agent retyping
the template. See guardrails.instructions.md.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TEMPLATE = HERE.parent / "xref-page.template.html"

# Every placeholder except {{XREF_JSON}}, which carries the payload.
FIELDS = {
    "PROJECT": "The Gardener's Almanac",
    "H1": "Almanac Concordance",
    "EYEBROW": "Example · book-build-patterns",
    "DECK": "Every chapter in every built edition, traced back to the source file it came "
            "from — and every source file, traced forward to the pages it lands on. Read it "
            "in the direction you need: <em>what is this chapter made of</em>, or "
            "<em>what does this edit break</em>.",
    "BUILD_NOTE": "This is synthetic example data, not a real book — it exists so the page "
                  "renders on a fresh clone.",
    "ROLE_SLICED_GLOSS": "cut from a source file at build time",
    "ROLE_ADAPTED_GLOSS": "re-voiced by hand from a named source",
    "ROLE_AUTHORED_GLOSS": "written in the book folder",
    "PROVENANCE_NOTE": "Generated by <code>example/build-example.py</code> from "
                       "<code>example/fixture.json</code>. Page numbers are 1-based PDF page "
                       "indexes, <em>not</em> the printed folio: front matter in roman and an "
                       "arabic count restarting at the body put the printed folio behind the "
                       "index by the length of the front matter.",
    "REGEN_COMMAND": "./build-example.py",
}


def labels(rows: list[dict]) -> tuple[str, str]:
    """BOOK_LABELS and BOOK_SHORT as JS object literals, derived from the data.

    Deriving them beats hand-maintaining them: a new edition appears in the page
    the first time it appears in a build, rather than the first time someone
    remembers to add it here.
    """
    pretty = {}
    short = {}
    for r in rows:
        pretty[f"{r['book']}|{r['edition']}"] = f"{spaced(r['book'])} · {r['edition']}"
        short.setdefault(r["book"], initials(r["book"]))
    return json.dumps(pretty, ensure_ascii=False), json.dumps(short, ensure_ascii=False)


def spaced(slug: str) -> str:
    return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", slug.replace("_", " "))


def initials(slug: str) -> str:
    caps = re.findall(r"[A-Z]", spaced(slug))
    return "".join(caps[:3]) if len(caps) > 1 else slug[:2].upper()


def render(payload: dict) -> str:
    rows = payload["rows"]
    missing = [r["title"] for r in rows if r.get("pages") in (None, "", "?")]
    if missing:
        print(f"warning: {len(missing)} entries have no page range: "
              f"{', '.join(missing[:4])}{' …' if len(missing) > 4 else ''}", file=sys.stderr)

    unknown = {r["pdf"] for r in rows} - set(payload["totals"])
    if unknown:
        sys.exit(f"error: rows reference PDFs missing from totals: {sorted(unknown)}")

    book_labels, book_short = labels(rows)
    out = TEMPLATE.read_text(encoding="utf-8")
    for key, value in FIELDS.items():
        out = out.replace("{{" + key + "}}", value)
    out = out.replace("{{BOOK_LABELS}}", book_labels)
    out = out.replace("{{BOOK_SHORT}}", book_short)

    # A literal </script> inside the JSON block would close it early.
    blob = json.dumps(payload, ensure_ascii=False, indent=1).replace("<", "\\u003c")
    out = out.replace("{{XREF_JSON}}", blob)

    body = out.split("-->", 1)[1]
    left = sorted(set(re.findall(r"\{\{[A-Z_0-9]+\}\}", body)))
    if left:
        sys.exit(f"error: unfilled placeholders: {', '.join(left)}")
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--data", type=Path, default=HERE / "fixture.json")
    ap.add_argument("--out", type=Path, default=HERE / "index.html")
    ap.add_argument("--check", action="store_true",
                    help="fail if the output would change; writes nothing")
    args = ap.parse_args()

    page = render(json.loads(args.data.read_text(encoding="utf-8")))

    if args.check:
        if not args.out.is_file():
            sys.exit(f"error: {args.out} does not exist — run without --check")
        if args.out.read_text(encoding="utf-8") != page:
            sys.exit(f"error: {args.out} is stale — run {Path(__file__).name} and commit")
        print(f"{args.out.name} is up to date")
        return

    args.out.write_text(page, encoding="utf-8")
    print(f"wrote {args.out} ({len(page):,} bytes)")


if __name__ == "__main__":
    main()
